### PR TITLE
Propose Ruben Verborgh as editor for the specification entry document

### PR DESCRIPTION
**Pull request by RubenVerborgh**
With this PR, I am proposing myself as an editor for the entry document to the Solid specification.

**This is _not_ a proposal for changing the process.**
Instead, this PR is a change compatible with the existing process.

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
This leaves a lot open in the readme text around how editors interact and what the categories of scope are.

**Comment by Mitzi-Laszlo** [comment]
It's also important to raise process proposal changes in the W3C Solid calls of both time zones to give others a chance to chip in and voice their opinions

**Comment by RubenVerborgh** [comment]
Note that I'm not proposing any process changes. The current process can be implemented in multiple ways; this is one way that could be meaningful.

**Comment by Mitzi-Laszlo** [comment]
Yes you are, you are talking about scope which is very important. Editors.md is under the culture repo which is where the process conversations happen.

**Comment by Mitzi-Laszlo** [comment]
The reason why I am insisting is that if there is an example of changes happening in .md files within the culture repo then that can happen multiple times by anyone which will destabilise the agreements and make is difficult to progress with legitimacy.

**Comment by RubenVerborgh** [comment]
> The reason why I am insisting is that if there is an example of changes happening in .md files within the culture repo

#26, #29, #30, #34 are changes; such changes are permitted by the process.

This PR #37 is also a change permitted by the process.

**Comment by Mitzi-Laszlo** [comment]
#26, #29, #30, #34 are applications to roles in the current process. 

This pull request is a change to the process. 

Deciding who has a voice on what is the fundamental question being answered in the process. 

Yes, indeed a change to the process is possible.

**Comment by Mitzi-Laszlo** [comment]
My suggestion on how to improve this process proposal are: 

You could categorise the editors by the points defined in the current process i.e. Solid Specification, Solid Roadmap, and Supporting Documentation. 

If you did this the other two categories would need to be included in the editors.md as headings. 

A few explanations would need to be defined in the readme, including: 
* a definition of where one category starts and the other ends
* which editors have a voice in what needs to be clearly stated 
* some mechanism needs to be in place for when editors of the Solid Specification, Solid Roadmap, and Supporting Documentation disagree and the three categories diverge

**Comment by Mitzi-Laszlo** [comment]
Perhaps this would be something you could raise in the coming W3C calls to cover the two time zones? @RubenVerborgh

**Comment by RubenVerborgh** [comment]
This PR constitutes a change compliant with https://github.com/solid/culture/blob/master/README.md#becoming-an-editor, and per the text there should be reviewed directly by the Solid Director.

**Comment by michielbdejong** [comment]
Didn't we agree in https://www.w3.org/community/solid/wiki/Meetings#20190711_1000CEST that @RubenVerborgh , @csarven and @kjetilk would become an *expert panel* on spec structure? And also that very explicitly that was just a mandate to change only the structure and not add/remove sections/components?

So then I don't think we need different editors for different documents, that is already what the expert panels do, right?

**Comment by RubenVerborgh** [comment]
I have decided to retract my application. I don't need to be in any list, I'll just work.

**Pull request closed without merging**
